//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppBase.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is a tool to bring training resources closer to people for daily use..
        /// </summary>
        internal static string AboutLabel_Text {
            get {
                return ResourceManager.GetString("AboutLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此操作將重新啟動應用程序!.
        /// </summary>
        internal static string ActionWillRestartApplicationInChinese_Text {
            get {
                return ResourceManager.GetString("ActionWillRestartApplicationInChinese.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato akce restartuje aplikaci!.
        /// </summary>
        internal static string ActionWillRestartApplicationInCzech_Text {
            get {
                return ResourceManager.GetString("ActionWillRestartApplicationInCzech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will restart the application!.
        /// </summary>
        internal static string ActionWillRestartApplicationInEnglish_Text {
            get {
                return ResourceManager.GetString("ActionWillRestartApplicationInEnglish.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette action redémarrera l&apos;application!.
        /// </summary>
        internal static string ActionWillRestartApplicationInFrench_Text {
            get {
                return ResourceManager.GetString("ActionWillRestartApplicationInFrench.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Aktion startet die Anwendung neu!.
        /// </summary>
        internal static string ActionWillRestartApplicationInGerman_Text {
            get {
                return ResourceManager.GetString("ActionWillRestartApplicationInGerman.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        internal static string albanianLabel_Text {
            get {
                return ResourceManager.GetString("albanianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string arabicLabel_Text {
            get {
                return ResourceManager.GetString("arabicLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string AutomaticOptionLabel_Text {
            get {
                return ResourceManager.GetString("AutomaticOptionLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijani.
        /// </summary>
        internal static string azerbaijaniLabel_Text {
            get {
                return ResourceManager.GetString("azerbaijaniLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        internal static string bulgarianLabel_Text {
            get {
                return ResourceManager.GetString("bulgarianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Kurdish.
        /// </summary>
        internal static string centralKurdishLabel_Text {
            get {
                return ResourceManager.GetString("centralKurdishLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string chineseLabel_Text {
            get {
                return ResourceManager.GetString("chineseLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you are connected to Internet as resources need to be downloaded..
        /// </summary>
        internal static string connectionLabel_Text {
            get {
                return ResourceManager.GetString("connectionLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string croatianLabel_Text {
            get {
                return ResourceManager.GetString("croatianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string czechLabel_Text {
            get {
                return ResourceManager.GetString("czechLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download_Text {
            get {
                return ResourceManager.GetString("Download.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you have connection to the Internet and hit the download button..
        /// </summary>
        internal static string DownloadInfoText_Text {
            get {
                return ResourceManager.GetString("DownloadInfoText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading selected resources ....
        /// </summary>
        internal static string DownloadingSelectedResourcesLabel_Text {
            get {
                return ResourceManager.GetString("DownloadingSelectedResourcesLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string dutchLabel_Text {
            get {
                return ResourceManager.GetString("dutchLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string englishLabel_Text {
            get {
                return ResourceManager.GetString("englishLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        internal static string estonianLabel_Text {
            get {
                return ResourceManager.GetString("estonianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Settings.
        /// </summary>
        internal static string FormatButton_Text {
            get {
                return ResourceManager.GetString("FormatButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of the resources.
        /// </summary>
        internal static string FormatSelectionLabel_Text {
            get {
                return ResourceManager.GetString("FormatSelectionLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string frenchLabel_Text {
            get {
                return ResourceManager.GetString("frenchLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        internal static string georgianLabel_Text {
            get {
                return ResourceManager.GetString("georgianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string germanLabel_Text {
            get {
                return ResourceManager.GetString("germanLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hausa.
        /// </summary>
        internal static string hausaLabel_Text {
            get {
                return ResourceManager.GetString("hausaLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        internal static string hindiLabel_Text {
            get {
                return ResourceManager.GetString("hindiLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Resources.
        /// </summary>
        internal static string HTMLResourcesLabel_Text {
            get {
                return ResourceManager.GetString("HTMLResourcesLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        internal static string hungarianLabel_Text {
            get {
                return ResourceManager.GetString("hungarianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        internal static string indonesianLabel_Text {
            get {
                return ResourceManager.GetString("indonesianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isiXhosa.
        /// </summary>
        internal static string isiXhosaLabel_Text {
            get {
                return ResourceManager.GetString("isiXhosaLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string italianLabel_Text {
            get {
                return ResourceManager.GetString("italianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kannada.
        /// </summary>
        internal static string kannadaLabel_Text {
            get {
                return ResourceManager.GetString("kannadaLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiswahili.
        /// </summary>
        internal static string kiswahiliLabel_Text {
            get {
                return ResourceManager.GetString("kiswahiliLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string koreanLabel_Text {
            get {
                return ResourceManager.GetString("koreanLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyz.
        /// </summary>
        internal static string kyrgyzLabel_Text {
            get {
                return ResourceManager.GetString("kyrgyzLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        internal static string LanguageChangeLabel_Text {
            get {
                return ResourceManager.GetString("LanguageChangeLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您想更改應用程序的語言嗎?.
        /// </summary>
        internal static string LanguageChangeQuestionInChinese_Text {
            get {
                return ResourceManager.GetString("LanguageChangeQuestionInChinese.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete změnit jazyk aplikace?.
        /// </summary>
        internal static string LanguageChangeQuestionInCzech_Text {
            get {
                return ResourceManager.GetString("LanguageChangeQuestionInCzech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to change language of the application?.
        /// </summary>
        internal static string LanguageChangeQuestionInEnglish_Text {
            get {
                return ResourceManager.GetString("LanguageChangeQuestionInEnglish.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhaitez-vous changer la langue de l&apos;application?.
        /// </summary>
        internal static string LanguageChangeQuestionInFrench_Text {
            get {
                return ResourceManager.GetString("LanguageChangeQuestionInFrench.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die Sprache der Anwendung ändern?.
        /// </summary>
        internal static string LanguageChangeQuestionInGerman_Text {
            get {
                return ResourceManager.GetString("LanguageChangeQuestionInGerman.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources&apos; language.
        /// </summary>
        internal static string LanguageOfResourcesLabel_Text {
            get {
                return ResourceManager.GetString("LanguageOfResourcesLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malayalam.
        /// </summary>
        internal static string malayalamLabel_Text {
            get {
                return ResourceManager.GetString("malayalamLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malay.
        /// </summary>
        internal static string malayLabel_Text {
            get {
                return ResourceManager.GetString("malayLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是的.
        /// </summary>
        internal static string NoInChinese_Text {
            get {
                return ResourceManager.GetString("NoInChinese.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string NoInCzech_Text {
            get {
                return ResourceManager.GetString("NoInCzech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoInEnglish_Text {
            get {
                return ResourceManager.GetString("NoInEnglish.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string NoInFrench_Text {
            get {
                return ResourceManager.GetString("NoInFrench.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string NoInGerman_Text {
            get {
                return ResourceManager.GetString("NoInGerman.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you have access to internet and try again..
        /// </summary>
        internal static string NoInternetMessage_Text {
            get {
                return ResourceManager.GetString("NoInternetMessage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian (Bokmål).
        /// </summary>
        internal static string norwegianBokmalLabel_Text {
            get {
                return ResourceManager.GetString("norwegianBokmalLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODT Resources.
        /// </summary>
        internal static string ODTResourcesLabel_Text {
            get {
                return ResourceManager.GetString("ODTResourcesLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a month.
        /// </summary>
        internal static string OnceAMonthOptionLabel_Text {
            get {
                return ResourceManager.GetString("OnceAMonthOptionLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On request.
        /// </summary>
        internal static string OnRequestOptionLabel_Text {
            get {
                return ResourceManager.GetString("OnRequestOptionLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pashto.
        /// </summary>
        internal static string pashtoLabel_Text {
            get {
                return ResourceManager.GetString("pashtoLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Resources.
        /// </summary>
        internal static string PDFResourcesLabel_Text {
            get {
                return ResourceManager.GetString("PDFResourcesLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        internal static string persianLabel_Text {
            get {
                return ResourceManager.GetString("persianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string polishLabel_Text {
            get {
                return ResourceManager.GetString("polishLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        internal static string portugueseBrazilLabel_Text {
            get {
                return ResourceManager.GetString("portugueseBrazilLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string portugueseLabel_Text {
            get {
                return ResourceManager.GetString("portugueseLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Request.
        /// </summary>
        internal static string RequestUpdateButton_Text {
            get {
                return ResourceManager.GetString("RequestUpdateButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string ResourcesButton_Text {
            get {
                return ResourceManager.GetString("ResourcesButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources Downloaded.
        /// </summary>
        internal static string ResourcesDownloadedMessage_Text {
            get {
                return ResourceManager.GetString("ResourcesDownloadedMessage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ResourcesDownloadedTitle_Text {
            get {
                return ResourceManager.GetString("ResourcesDownloadedTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful download. Pleas make sure you have Internet access..
        /// </summary>
        internal static string ResourcesDownloadedUnsuccessful_Text {
            get {
                return ResourceManager.GetString("ResourcesDownloadedUnsuccessful.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading of resources started. This may take a while, please wait until message about the result shows up..
        /// </summary>
        internal static string ResourcesDownloadStartMessage_Text {
            get {
                return ResourceManager.GetString("ResourcesDownloadStartMessage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting download.
        /// </summary>
        internal static string ResourcesDownloadStartTitle_Text {
            get {
                return ResourceManager.GetString("ResourcesDownloadStartTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        internal static string romanianLabel_Text {
            get {
                return ResourceManager.GetString("romanianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string russianLabel_Text {
            get {
                return ResourceManager.GetString("russianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton_Text {
            get {
                return ResourceManager.GetString("SaveButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select the language of the application..
        /// </summary>
        internal static string selectAppLanguageLabel_Text {
            get {
                return ResourceManager.GetString("selectAppLanguageLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select the format of resources you wish to save..
        /// </summary>
        internal static string selectFormatOfResourcesLabel_Text {
            get {
                return ResourceManager.GetString("selectFormatOfResourcesLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select the resource languages you are interested in..
        /// </summary>
        internal static string selectResourceLanguagesLabel_Text {
            get {
                return ResourceManager.GetString("selectResourceLanguagesLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        internal static string serbianLabel_Text {
            get {
                return ResourceManager.GetString("serbianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsButton_Text {
            get {
                return ResourceManager.GetString("SettingsButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareButton_Text {
            get {
                return ResourceManager.GetString("ShareButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        internal static string slovakLabel_Text {
            get {
                return ResourceManager.GetString("slovakLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        internal static string slovenianLabel_Text {
            get {
                return ResourceManager.GetString("slovenianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string spanishLabel_Text {
            get {
                return ResourceManager.GetString("spanishLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string swedishLabel_Text {
            get {
                return ResourceManager.GetString("swedishLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        internal static string tamilLabel_Text {
            get {
                return ResourceManager.GetString("tamilLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telugu.
        /// </summary>
        internal static string teluguLabel_Text {
            get {
                return ResourceManager.GetString("teluguLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string thaiLabel_Text {
            get {
                return ResourceManager.GetString("thaiLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tigrinya.
        /// </summary>
        internal static string tigrinyaLabel_Text {
            get {
                return ResourceManager.GetString("tigrinyaLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string turkishLabel_Text {
            get {
                return ResourceManager.GetString("turkishLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string ukrainianLabel_Text {
            get {
                return ResourceManager.GetString("ukrainianLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval Settings.
        /// </summary>
        internal static string UpdateIntervalSettingsLabel_Text {
            get {
                return ResourceManager.GetString("UpdateIntervalSettingsLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        internal static string urduLabel_Text {
            get {
                return ResourceManager.GetString("urduLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek (Cyrillic).
        /// </summary>
        internal static string uzbekCyrillicLabel_Text {
            get {
                return ResourceManager.GetString("uzbekCyrillicLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek.
        /// </summary>
        internal static string uzbekLabel_Text {
            get {
                return ResourceManager.GetString("uzbekLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string vietnameseLabel_Text {
            get {
                return ResourceManager.GetString("vietnameseLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download only when wifi is on.
        /// </summary>
        internal static string WifiLabel_Text {
            get {
                return ResourceManager.GetString("WifiLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是的.
        /// </summary>
        internal static string YesInChinese_Text {
            get {
                return ResourceManager.GetString("YesInChinese.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        internal static string YesInCzech_Text {
            get {
                return ResourceManager.GetString("YesInCzech.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesInEnglish_Text {
            get {
                return ResourceManager.GetString("YesInEnglish.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string YesInFrench_Text {
            get {
                return ResourceManager.GetString("YesInFrench.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string YesInGerman_Text {
            get {
                return ResourceManager.GetString("YesInGerman.Text", resourceCulture);
            }
        }
    }
}
